name: Build, Test and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cmake_generator: "Unix Makefiles"
            build_type: Release
            artifact_name: hello-linux
          - os: macos-latest
            cmake_generator: "Unix Makefiles"
            build_type: Release
            artifact_name: hello-macos
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
            build_type: Release
            artifact_name: hello-windows.exe

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -G "${{ matrix.cmake_generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C ${{ matrix.build_type }} --verbose

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Package Executable
      shell: bash
      run: |
        mkdir -p ${{github.workspace}}/dist
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          cp ${{github.workspace}}/build/${{ matrix.build_type }}/hello_app.exe ${{github.workspace}}/dist/${{ matrix.artifact_name }}
        else
          cp ${{github.workspace}}/build/hello_app ${{github.workspace}}/dist/${{ matrix.artifact_name }}
        fi

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{github.workspace}}/dist/${{ matrix.artifact_name }}

  release:
    name: Create Release
    needs: build-and-test
    # Only run on tag push or main/master branch
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - name: Create Release Directory
      run: mkdir -p releases
      
    - name: Download All Artifacts
      uses: actions/download-artifact@v3
      with:
        path: releases
    
    - name: Display Structure
      run: ls -R releases

    - name: Create Release Name
      id: release_name
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "version=nightly-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.release_name.outputs.version }}
        tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || steps.release_name.outputs.version }}
        draft: false
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
        generate_release_notes: true
        files: |
          releases/hello-linux/hello-linux
          releases/hello-macos/hello-macos
          releases/hello-windows.exe/hello-windows.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
